### ISSUE TITLE
关于：预约验证码错误

### ISSUE THREAD

**Issue by Ray-Y0ung** [rwang5203/thu-badminton-reserve#2]
你好~最近球场十分难约，且会出现  预定失败：预约验证码错误 的失败信息，是因为需要添加自动识别验证码模块吗

**Comment by rwang2000** [comment]
同学你好，模型在我们测试后识别准确率为93.5%左右，因此你提到的“验证码错误”的情况是可能存在的，我们推荐你尽量多涵盖一些场地，以提高预约成功率，目前打算有空再去优化模型。感谢你提出的宝贵意见，祝你使用愉快！
